import assert from "node:assert/strict"
import { createHash } from "node:crypto"
import { readFileSync } from "node:fs"
import test from "node:test"
import { K6_R1_ROUTE_REQUEST_VERSION, canonicalK6R1Json, createK6R1RouteRequest } from "../src/evidence-router/contracts.ts"
import {
  K6_R5_FIXTURE_CANDIDATE_STRATEGY_ID, K6_R5_FIXTURE_INCUMBENT_STRATEGY_ID, K6_R5_LIMITS,
  K6_R5_PRIVACY_CLASSES, K6_R5_QUALIFICATION_CORPUS_ID, K6_R5_QUALIFICATION_CORPUS_VERSION,
  K6_R5_QUALIFICATION_OUTCOMES, K6_R5_QUALIFICATION_RESULT_VERSION, K6_R5_STRATEGY_EVIDENCE_VERSION,
  K6_R5_STRATEGY_KIND, K6_R5_STRATEGY_VERSION, type K6R5Strategy, type K6R5StrategyEvidence,
} from "../src/evidence-router/strategy-proposal-contracts.ts"
import {
  compareK6R5Strategies, createK6R5Strategy, createK6R5StrategyEvidence, deriveK6R5TaskFamilyIdentity,
  k6R5QualificationResultIdentity, k6R5StrategyEvidenceIdentity, k6R5StrategyIdentity, k6R5TrialSetIdentity,
  validateK6R5QualificationResult, validateK6R5Strategy, validateK6R5StrategyEvidence,
} from "../src/evidence-router/strategy-proposal.ts"

const A="a".repeat(64),B="b".repeat(64),C="c".repeat(64),D="d".repeat(64),E="e".repeat(64),F="f".repeat(64),Z="0".repeat(64)
const S=Object.freeze({repositoryIdentity:"1".repeat(64),revisionIdentity:"2".repeat(64),ownerScopeId:"3".repeat(64),privacyClass:"REPOSITORY_PRIVATE" as const,taskFamilyIdentity:"4".repeat(64)})
const T=Object.freeze(["5".repeat(64),"6".repeat(64),"7".repeat(64),"8".repeat(64)])
const strat=(order:readonly string[]):K6R5Strategy=>createK6R5Strategy({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:S,orderedCandidateIdentities:[...order]})
const I=strat([A,B]), N=strat([B,A]), TS=k6R5TrialSetIdentity(K6_R5_QUALIFICATION_CORPUS_ID,T)
function ev(s:K6R5Strategy,m:Record<string,number>={},o:Record<string,unknown>={}):K6R5StrategyEvidence{return createK6R5StrategyEvidence({version:K6_R5_STRATEGY_EVIDENCE_VERSION,strategyIdentity:s.strategyIdentity,scope:s.scope,qualificationCorpusIdentity:K6_R5_QUALIFICATION_CORPUS_ID,trialSetIdentity:TS,trialCaseIdentities:[...T],trialCount:4,verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:400,computeUnitsTotal:40,privacyViolationCount:0,securityViolationCount:0,verificationEvidenceIdentity:A,k5EvidenceIdentity:B,doneGateEvidenceIdentity:C,latencyEvidenceIdentity:D,computeEvidenceIdentity:E,privacyEvidenceIdentity:F,securityEvidenceIdentity:Z,...m,...o})}
const CASES=[
 ["quality-dominance","CANDIDATE_DOMINATES",{verifiedPassCount:3,k5ValidCount:3,doneReadyCount:2,latencyTotalMs:400,computeUnitsTotal:40},{verifiedPassCount:4,k5ValidCount:3,doneReadyCount:2,latencyTotalMs:400,computeUnitsTotal:40}],
 ["resource-dominance","CANDIDATE_DOMINATES",{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:400,computeUnitsTotal:40},{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:360,computeUnitsTotal:36}],
 ["incumbent-dominance","INCUMBENT_DOMINATES",{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:3,latencyTotalMs:380,computeUnitsTotal:38},{verifiedPassCount:3,k5ValidCount:3,doneReadyCount:3,latencyTotalMs:390,computeUnitsTotal:39}],
 ["exact-tie","TIE",{verifiedPassCount:4,k5ValidCount:3,doneReadyCount:3,latencyTotalMs:380,computeUnitsTotal:38},{verifiedPassCount:4,k5ValidCount:3,doneReadyCount:3,latencyTotalMs:380,computeUnitsTotal:38}],
 ["mixed-tradeoff","INCOMPARABLE",{verifiedPassCount:3,k5ValidCount:3,doneReadyCount:3,latencyTotalMs:360,computeUnitsTotal:36},{verifiedPassCount:4,k5ValidCount:3,doneReadyCount:3,latencyTotalMs:400,computeUnitsTotal:40}],
 ["candidate-privacy-invalid","CANDIDATE_INVALID",{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:400,computeUnitsTotal:40},{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:350,computeUnitsTotal:35,privacyViolationCount:1}],
 ["both-invalid","BOTH_INVALID",{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:400,computeUnitsTotal:40,securityViolationCount:1},{verifiedPassCount:4,k5ValidCount:4,doneReadyCount:4,latencyTotalMs:350,computeUnitsTotal:35,privacyViolationCount:1}],
] as const
const CORPUS={candidateStrategy:{kind:K6_R5_STRATEGY_KIND,orderedCandidateIdentities:[B,A],scope:S,strategyIdentity:K6_R5_FIXTURE_CANDIDATE_STRATEGY_ID,version:K6_R5_STRATEGY_VERSION},cases:CASES.map(([caseId,expected,incumbent,candidate])=>({candidate:{...candidate,privacyViolationCount:"privacyViolationCount" in candidate?candidate.privacyViolationCount:0,securityViolationCount:"securityViolationCount" in candidate?candidate.securityViolationCount:0,trialCount:4},caseId,expected,incumbent:{...incumbent,privacyViolationCount:"privacyViolationCount" in incumbent?incumbent.privacyViolationCount:0,securityViolationCount:"securityViolationCount" in incumbent?incumbent.securityViolationCount:0,trialCount:4}})),incumbentStrategy:{kind:K6_R5_STRATEGY_KIND,orderedCandidateIdentities:[A,B],scope:S,strategyIdentity:K6_R5_FIXTURE_INCUMBENT_STRATEGY_ID,version:K6_R5_STRATEGY_VERSION},version:K6_R5_QUALIFICATION_CORPUS_VERSION}
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T
const candidate=()=>({candidateId:"candidate-a",candidateKind:"MODEL_PROVIDER",provider:"provider",model:"model",declaredCapabilities:["repo/search","model/generate"],maximumRiskClass:"HIGH",supportedPrivacyClasses:["PUBLIC","REPOSITORY_PRIVATE"],qualification:{protocol:"kodac.provider-qualification",version:1,provider:"provider",model:"model",workspaceDigest:A,status:"PASS",reportDigest:B}})
const request=(caps=["repo/search","model/generate"])=>({version:K6_R1_ROUTE_REQUEST_VERSION,repositoryId:"TheHalfMoon/Kodac",canonicalBase:"0".repeat(40),candidateHead:"1".repeat(40),taskId:"r5/task-family",riskClass:"MEDIUM",privacyClass:"REPOSITORY_PRIVATE",requiredCapabilities:caps,candidates:[candidate()]})

test("closed vocabularies are exact and immutable",()=>{assert.equal(K6_R5_STRATEGY_VERSION,"kodac-k6-r5-strategy-v1");assert.equal(K6_R5_STRATEGY_EVIDENCE_VERSION,"kodac-k6-r5-strategy-evidence-v1");assert.equal(K6_R5_QUALIFICATION_RESULT_VERSION,"kodac-k6-r5-qualification-result-v1");assert.equal(K6_R5_QUALIFICATION_CORPUS_VERSION,"kodac-k6-r5-qualification-corpus-v1");assert.equal(K6_R5_STRATEGY_KIND,"EXPLICIT_ELIGIBLE_CANDIDATE_ORDER");assert.deepEqual(K6_R5_PRIVACY_CLASSES,["PUBLIC","REPOSITORY_PRIVATE","SENSITIVE"]);assert.deepEqual(K6_R5_QUALIFICATION_OUTCOMES,["BOTH_INVALID","CANDIDATE_INVALID","INCUMBENT_INVALID","CANDIDATE_DOMINATES","INCUMBENT_DOMINATES","TIE","INCOMPARABLE"]);assert.ok(Object.isFrozen(K6_R5_PRIVACY_CLASSES)&&Object.isFrozen(K6_R5_QUALIFICATION_OUTCOMES))})

test("schema/runtime parity closes objects, vocabularies, limits, and non-zero trial counts",()=>{const x=JSON.parse(readFileSync(new URL("../../../schema/k6-r5-bounded-strategy-proposal.schema.json",import.meta.url),"utf8")),$=x.$defs;assert.equal(x.$ref,"#/$defs/qualificationResult");assert.deepEqual($.privacyClass.enum,[...K6_R5_PRIVACY_CLASSES]);assert.deepEqual($.qualificationResult.properties.outcome.enum,[...K6_R5_QUALIFICATION_OUTCOMES]);assert.equal($.strategy.properties.version.const,K6_R5_STRATEGY_VERSION);assert.equal($.strategyEvidence.properties.version.const,K6_R5_STRATEGY_EVIDENCE_VERSION);assert.equal($.qualificationResult.properties.version.const,K6_R5_QUALIFICATION_RESULT_VERSION);assert.equal($.strategy.properties.kind.const,K6_R5_STRATEGY_KIND);assert.equal($.strategy.properties.orderedCandidateIdentities.maxItems,128);assert.equal($.strategyEvidence.properties.trialCaseIdentities.maxItems,128);assert.equal($.positiveSafeInteger.minimum,1);for(const v of Object.values($) as Record<string,unknown>[])if(v.type==="object")assert.equal(v.additionalProperties,false)})

test("fixture strategy identities recompute exactly",()=>{assert.equal(I.strategyIdentity,K6_R5_FIXTURE_INCUMBENT_STRATEGY_ID);assert.equal(N.strategyIdentity,K6_R5_FIXTURE_CANDIDATE_STRATEGY_ID);assert.equal(k6R5StrategyIdentity({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:S,orderedCandidateIdentities:[A,B]}),I.strategyIdentity);assert.equal(validateK6R5Strategy(I).strategyIdentity,I.strategyIdentity)})

test("fixed qualification corpus identity recomputes exactly",()=>assert.equal(createHash("sha256").update(canonicalK6R1Json(CORPUS),"utf8").digest("hex"),K6_R5_QUALIFICATION_CORPUS_ID))

test("trial-set identity is deterministic, ordered, corpus-bound, and non-empty",()=>{const e=createHash("sha256").update(canonicalK6R1Json({kind:"K6_R5_TRIAL_SET",qualificationCorpusIdentity:K6_R5_QUALIFICATION_CORPUS_ID,trialCaseIdentities:T}),"utf8").digest("hex");assert.equal(TS,e);assert.notEqual(k6R5TrialSetIdentity(K6_R5_QUALIFICATION_CORPUS_ID,[...T].reverse()),e);assert.throws(()=>k6R5TrialSetIdentity(K6_R5_QUALIFICATION_CORPUS_ID,[]),RangeError)})

test("task-family identity derives only from a validated R1 request",()=>{const r=createK6R1RouteRequest(request()),actual=deriveK6R5TaskFamilyIdentity(r),expected=createHash("sha256").update(canonicalK6R1Json({kind:"K6_R5_TASK_FAMILY",riskClass:r.riskClass,privacyClass:r.privacyClass,requiredCapabilities:r.requiredCapabilities}),"utf8").digest("hex");assert.equal(actual,expected);assert.equal(deriveK6R5TaskFamilyIdentity(createK6R1RouteRequest(request(["model/generate","repo/search"]))),actual);assert.throws(()=>deriveK6R5TaskFamilyIdentity({...r,requestIdentity:F}),TypeError)})

test("all seven fixed qualification corpus outcomes and separate INCUMBENT_INVALID obey precedence",()=>{for(const [id,w,i,n] of CASES)assert.equal(compareK6R5Strategies(I,N,ev(I,{...i}),ev(N,{...n})).outcome,w,id);assert.equal(compareK6R5Strategies(I,N,ev(I,{privacyViolationCount:1}),ev(N,{verifiedPassCount:0,k5ValidCount:0,doneReadyCount:0,latencyTotalMs:999,computeUnitsTotal:999})).outcome,"INCUMBENT_INVALID")})

test("structural mismatch fails before producing a qualification result",()=>{const i=ev(I),n=ev(N);assert.throws(()=>compareK6R5Strategies(I,N,i,ev(N,{}, {qualificationCorpusIdentity:"9".repeat(64),trialSetIdentity:k6R5TrialSetIdentity("9".repeat(64),T)})),/qualification corpus/);const rt=[T[0]!,T[1]!,T[3]!,T[2]!];assert.throws(()=>compareK6R5Strategies(I,N,i,ev(N,{}, {trialCaseIdentities:rt,trialSetIdentity:k6R5TrialSetIdentity(K6_R5_QUALIFICATION_CORPUS_ID,rt)})),/trial-set|trial-case/);assert.throws(()=>compareK6R5Strategies(I,N,i,{...n,strategyIdentity:I.strategyIdentity}),TypeError);const other=strat([A]);assert.throws(()=>compareK6R5Strategies(I,other,i,ev(other)),/candidate identity sets/)})

test("identities are deterministic and results contain no promotion authority",()=>{const i=ev(I,{verifiedPassCount:3}),n=ev(N,{verifiedPassCount:4}),r=compareK6R5Strategies(I,N,i,n),ii={...clone(i)} as Record<string,unknown>;delete ii.evidenceIdentity;assert.equal(k6R5StrategyEvidenceIdentity(ii),i.evidenceIdentity);assert.equal(validateK6R5StrategyEvidence(i).evidenceIdentity,i.evidenceIdentity);const ri={...r} as Record<string,unknown>;delete ri.resultIdentity;assert.equal(k6R5QualificationResultIdentity(ri),r.resultIdentity);assert.equal(validateK6R5QualificationResult(r).resultIdentity,r.resultIdentity);assert.deepEqual(Object.keys(r),["version","resultIdentity","incumbentStrategyIdentity","candidateStrategyIdentity","incumbentEvidenceIdentity","candidateEvidenceIdentity","qualificationCorpusIdentity","trialSetIdentity","trialCount","outcome"]);for(const k of ["promote","winnerForProduction","approved","DONE","PROVEN_READY","score","reward"])assert.equal(Object.hasOwn(r,k),false)})

test("hostile inputs, numeric/resource bounds, and caller mutation fail closed while outputs stay immutable",()=>{let traps=0;const p=new Proxy(S as object,{getPrototypeOf(){traps++;throw Error("trap")},ownKeys(){traps++;throw Error("trap")},getOwnPropertyDescriptor(){traps++;throw Error("trap")}});assert.throws(()=>createK6R5Strategy({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:p,orderedCandidateIdentities:[A]}),/Proxy/);assert.equal(traps,0);const a={version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:S,orderedCandidateIdentities:[A]} as Record<string,unknown>;Object.defineProperty(a,"kind",{enumerable:true,get(){return K6_R5_STRATEGY_KIND}});assert.throws(()=>createK6R5Strategy(a),TypeError);const sy={version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:S,orderedCandidateIdentities:[A]};Object.defineProperty(sy,Symbol("x"),{enumerable:true,value:1});assert.throws(()=>createK6R5Strategy(sy),TypeError);const sparse=new Array(2);sparse[0]=A;assert.throws(()=>createK6R5Strategy({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:S,orderedCandidateIdentities:sparse}),TypeError);const cyc:Record<string,unknown>={...S};cyc.self=cyc;assert.throws(()=>createK6R5Strategy({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope:cyc,orderedCandidateIdentities:[A]}),/cyclic/);for(const bad of [-1,-0,1.5,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>ev(I,{latencyTotalMs:bad}),TypeError);assert.throws(()=>ev(I,{verifiedPassCount:5}),TypeError);assert.throws(()=>strat(Array.from({length:129},(_,x)=>x.toString(16).padStart(64,"0"))),RangeError);assert.equal(K6_R5_LIMITS.maxCanonicalDepth,32);assert.equal(K6_R5_LIMITS.maxCanonicalNodes,50000);const scope={...S},order=[A,B],v=createK6R5Strategy({version:K6_R5_STRATEGY_VERSION,kind:K6_R5_STRATEGY_KIND,scope,orderedCandidateIdentities:order});scope.revisionIdentity=F;order.reverse();assert.equal(v.scope.revisionIdentity,S.revisionIdentity);assert.deepEqual(v.orderedCandidateIdentities,[A,B]);assert.ok(Object.isFrozen(v)&&Object.isFrozen(v.scope)&&Object.isFrozen(v.orderedCandidateIdentities))})

test("there is no weighted reward, random, clock, provider, persistence, network, or automatic-promotion path",()=>{const c=readFileSync(new URL("../src/evidence-router/strategy-proposal-contracts.ts",import.meta.url),"utf8"),r=readFileSync(new URL("../src/evidence-router/strategy-proposal.ts",import.meta.url),"utf8"),s=`${c}\n${r}`;for(const p of [/weighted/i,/reward/i,/Math\.random/,/Date\.now/,/\bfetch\s*\(/,/node:http/,/node:https/,/node:fs/,/database/i,/telemetry/i,/automatic.?promotion/i,/winnerForProduction/i])assert.equal(p.test(s),false,String(p))})
