import { createHash } from "node:crypto"
import { existsSync, readFileSync } from "node:fs"
import assert from "node:assert/strict"
import test from "node:test"
import { acquireO4bBoundedReadOnlyGithubContext, type O4bBoundedReadOnlyGithubContextInput } from "../src/github-review/o4b-bounded-read-only-github-context.ts"
import { buildO4cGithubReviewerContext } from "../src/github-review/o4c-github-context-to-reviewer-context.ts"
import {
  O4D_ADMISSION_RESULT_KEYS, O4D_CONTINUATION_DECISIONS, O4D_EXECUTION_READY_ITEM_KEYS,
  O4D_READY_DECISION, O4D_REVIEWER_EXECUTION_ADMISSION_VERSION,
  createO4dO4cReviewerExecutionAdmission, validateO4dO4cReviewerExecutionAdmissionResult,
} from "../src/github-review/o4d-o4c-reviewer-execution-admission.ts"

type Obj=Record<string,any>
const BASE="a".repeat(40), HEAD="b".repeat(40), REPO_ID="1001", PR_ID="2002", REPO="TheHalfMoon/Kodac", PR=42, POLICY="d".repeat(64), PRIMARY="src/widget.ts"
const BYTES=new TextEncoder().encode("export const widget = 1\n")
const sha256=(v:Uint8Array|string)=>createHash("sha256").update(v).digest("hex")
const blobSha=(b:Uint8Array)=>createHash("sha1").update(`blob ${b.byteLength}\0`,"utf8").update(b).digest("hex")
const fileBody=(path:string,b:Uint8Array)=>({type:"file",encoding:"base64",path,sha:blobSha(b),size:b.byteLength,content:Buffer.from(b).toString("base64")})
const changed=(path=PRIMARY,status="modified",b=BYTES,extra:Obj={})=>({filename:path,status,sha:blobSha(b),...extra})
function fixture(opts:{fork?:boolean,rows?:Obj[],support?:string[],content?:Record<string,Obj>}={}){
 const fork=opts.fork??false, rows=opts.rows??[changed()], content:Record<string,Obj>={[PRIMARY]:fileBody(PRIMARY,BYTES),...(opts.content??{})}
 for(const row of rows){const path=String(row.filename);if(!(path in content)){const b=new TextEncoder().encode(`content:${path}\n`);content[path]=fileBody(path,b);row.sha=content[path].sha}}
 for(const path of opts.support??[]) if(!(path in content)){const b=new TextEncoder().encode(`support:${path}\n`);content[path]=fileBody(path,b)}
 let prReads=0; const snap=()=>({id:Number(PR_ID),number:PR,base:{ref:"main",sha:BASE,repo:{id:Number(REPO_ID),full_name:REPO}},head:{ref:"feat",sha:HEAD,repo:{id:fork?9001:Number(REPO_ID),full_name:fork?"Contributor/Kodac":REPO}}})
 const fetchImpl=(async(raw:URL|RequestInfo)=>{const u=new URL(raw instanceof URL?raw.href:typeof raw==="string"?raw:raw.url);if(/\/pulls\/\d+$/.test(u.pathname)){prReads++;return new Response(JSON.stringify(snap()),{status:200,headers:{"content-type":"application/json"}})}if(/\/pulls\/\d+\/files$/.test(u.pathname))return new Response(JSON.stringify(Number(u.searchParams.get("page"))===1?rows:[]),{status:200,headers:{"content-type":"application/json"}});if(u.pathname.includes("/contents/")){const m="/contents/", path=u.pathname.slice(u.pathname.indexOf(m)+m.length).split("/").map(decodeURIComponent).join("/");const body=content[path];return new Response(JSON.stringify(body??{message:"Not Found"}),{status:body?200:404,headers:{"content-type":"application/json"}})}return new Response(null,{status:404})}) as typeof fetch
 const input:O4bBoundedReadOnlyGithubContextInput={expectedRepositoryId:REPO_ID,expectedRepositoryFullName:REPO,pullRequestNumber:PR,expectedPullRequestId:PR_ID,expectedBaseRepositoryId:REPO_ID,expectedHeadRepositoryId:fork?"9001":REPO_ID,expectedHeadRepositoryFullName:fork?"Contributor/Kodac":REPO,expectedHeadSha:HEAD,credentialPolicyIdentity:POLICY,supportingPaths:opts.support??[],credential:"fixture"}
 let i=0;const times=["2026-09-11T01:00:00.000Z","2026-09-11T01:00:01.000Z"];return acquireO4bBoundedReadOnlyGithubContext(input,{fetchImpl,now:()=>times[Math.min(i++,1)]!})
}
async function context(opts:Parameters<typeof fixture>[0]={}){const o4b=await fixture(opts);return buildO4cGithubReviewerContext({taskId:"review-pr-42",objective:"Review exact changed paths.",o4bContext:o4b})}
const admission=(ctx:unknown,extra:Obj={})=>createO4dO4cReviewerExecutionAdmission({taskId:"review-pr-42",policyIdentity:"policy:v1",instructions:"Find evidence-grounded material defects only.",o4cContext:ctx,...extra})
const clone=<T>(x:T):T=>structuredClone(x)
function canonicalTest(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonicalTest).join(",")}]`;const r=value as Obj;return `{${Object.keys(r).sort().map(k=>`${JSON.stringify(k)}:${canonicalTest(r[k])}`).join(",")}}`}
function resign(value:Obj):Obj{const {admissionIdentity:_old,...rest}=value;value.admissionIdentity=createHash("sha256").update("o4d-reviewer-execution-admission-identity","utf8").update("\0","utf8").update(canonicalTest(rest),"utf8").digest("hex");return value}
function deepFrozen(v:unknown,seen=new Set<object>()){if(typeof v!=="object"||v===null||seen.has(v))return;seen.add(v);assert.equal(Object.isFrozen(v),true);for(const x of Object.values(v as Obj))deepFrozen(x,seen)}
const cases:Array<[string,()=>void|Promise<void>]>=[
 ["one changed path admits exact O4-C context",async()=>{const c=await context(),r=admission(c);assert.equal(r.continuationDecision,O4D_READY_DECISION);assert.deepEqual(r.changedPaths,[PRIMARY]);assert.equal(r.items.length,1)}],
 ["multiple changed paths preserve canonical sequence",async()=>{const c=await context({rows:[changed("z.ts"),changed("a.ts")]});const r=admission(c);assert.deepEqual(r.changedPaths,["a.ts","z.ts"]);assert.deepEqual(r.items.map(x=>x.subjectPath),["a.ts","z.ts"])}],
 ["fork context preserves predecessor identities",async()=>{const c=await context({fork:true}),r=admission(c);assert.equal(r.contextIdentity,c.contextIdentity);assert.equal(r.reviewedHead,HEAD)}],
 ["removed BASE_REMOVED metadata is preserved",async()=>{const c=await context({rows:[changed(PRIMARY,"removed")]});assert.equal(admission(c).items[0]?.contentRevisionKind,"BASE_REMOVED")}],
 ["renamed previousPath metadata is preserved",async()=>{const c=await context({rows:[changed(PRIMARY,"renamed",BYTES,{previous_filename:"src/old.ts"})]});assert.equal(admission(c).items[0]?.previousPath,"src/old.ts")}],
 ["supporting context is preserved after changed paths",async()=>{const r=admission(await context({support:["docs/context.md"]}));assert.deepEqual(r.items.map(x=>x.readRole),["CHANGED_PATH","SUPPORTING_CONTEXT"])}],
 ["deterministic repeat admission is byte identical",async()=>{const c=await context({support:["docs/context.md"]});const a=admission(c),b=admission(c);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(a.admissionIdentity,b.admissionIdentity)}],
 ["LF bytes are preserved exactly",async()=>{const r=admission(await context());assert.equal(r.items[0]?.text,"export const widget = 1\n");assert.equal(r.items[0]?.contentIdentity,sha256(BYTES))}],
 ["CRLF bytes are preserved exactly",async()=>{const b=new TextEncoder().encode("a\r\nb\r\n");const r=admission(await context({rows:[changed(PRIMARY,"modified",b)],content:{[PRIMARY]:fileBody(PRIMARY,b)}}));assert.equal(r.items[0]?.text,"a\r\nb\r\n");assert.equal(r.items[0]?.contextUtf8Bytes,b.byteLength)}],
 ["zero supporting context remains zero",async()=>{const r=admission(await context());assert.equal(r.omittedSupportingPathCount,0);assert.equal(r.items.filter(x=>x.readRole==="SUPPORTING_CONTEXT").length,0)}],
 ["instruction identity is deterministic and instruction-sensitive",async()=>{const c=await context(),a=admission(c),b=admission(c,{instructions:"Different instructions."});assert.equal(a.instructionsIdentity,sha256(a.instructions));assert.notEqual(a.instructionsIdentity,b.instructionsIdentity)}],
 ["canonical result is deeply frozen",async()=>deepFrozen(admission(await context({support:["docs/context.md"]})))],
 ["runtime validator accepts canonical output",async()=>{const r=admission(await context());assert.deepEqual(validateO4dO4cReviewerExecutionAdmissionResult(r),r)}],
 ["schema result and item key surfaces match runtime",()=>{const s=JSON.parse(readFileSync(new URL("../../../schema/o4d-o4c-reviewer-execution-admission.schema.json",import.meta.url),"utf8"));assert.deepEqual([...s.required].sort(),[...O4D_ADMISSION_RESULT_KEYS].sort());assert.deepEqual(Object.keys(s.properties).sort(),[...O4D_ADMISSION_RESULT_KEYS].sort());assert.deepEqual([...s.$defs.item.required].sort(),[...O4D_EXECUTION_READY_ITEM_KEYS].sort())}],
 ["schema constants mirror runtime constants",()=>{const s=JSON.parse(readFileSync(new URL("../../../schema/o4d-o4c-reviewer-execution-admission.schema.json",import.meta.url),"utf8"));assert.equal(s.properties.version.const,O4D_REVIEWER_EXECUTION_ADMISSION_VERSION);assert.deepEqual(s.properties.continuationDecision.enum,O4D_CONTINUATION_DECISIONS)}],
 ["blocked O4-C decision yields zero execution-ready items",async()=>{const bad=new Uint8Array([255]);const c=await context({rows:[changed(PRIMARY,"modified",bad)],content:{[PRIMARY]:fileBody(PRIMARY,bad)}});const r=admission(c);assert.notEqual(r.continuationDecision,O4D_READY_DECISION);assert.equal(r.items.length,0);assert.equal(r.itemCount,0)}],
 ["task mismatch blocks with zero items",async()=>{const r=admission(await context(),{taskId:"other"});assert.equal(r.continuationDecision,"BLOCK_TASK_ID_MISMATCH");assert.equal(r.items.length,0)}],
 ["invalid O4-C context identity fails closed",async()=>{const c=clone(await context()) as Obj;c.contextIdentity="f".repeat(64);assert.throws(()=>admission(c),/invalid O4-C context/)}],
 ["mutated predecessor item text fails closed",async()=>{const c=clone(await context()) as Obj;c.items[0].text+="x";assert.throws(()=>admission(c),/invalid O4-C context/)}],
 ["unknown input property fails closed",async()=>{const c=await context();assert.throws(()=>createO4dO4cReviewerExecutionAdmission({taskId:"t",policyIdentity:"p",instructions:"i",o4cContext:c,extra:true}),/unexpected or missing/)}],
 ["proxy input fails closed",async()=>{const x={taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:await context()};assert.throws(()=>createO4dO4cReviewerExecutionAdmission(new Proxy(x,{})),/proxy/)}],
 ["accessor input fails without invoking getter",async()=>{let n=0;const x:any={taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:await context()};Object.defineProperty(x,"instructions",{enumerable:true,get(){n++;return"i"}});assert.throws(()=>createO4dO4cReviewerExecutionAdmission(x),/accessor|data property/);assert.equal(n,0)}],
 ["symbol-key input fails closed",async()=>{const x:any={taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:await context()};x[Symbol("x")]=1;assert.throws(()=>createO4dO4cReviewerExecutionAdmission(x),/symbol/)}],
 ["unexpected prototype fails closed",async()=>{const x=Object.assign(Object.create({x:true}),{taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:await context()});assert.throws(()=>createO4dO4cReviewerExecutionAdmission(x),/prototype/)}],
 ["cyclic graph fails closed",async()=>{const x:any={taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:await context()};x.self=x;assert.throws(()=>createO4dO4cReviewerExecutionAdmission(x),/cyclic|unexpected/)}],
 ["aliased graph fails closed",async()=>{const c=await context();const x:any={taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:c};x.alias=c;assert.throws(()=>createO4dO4cReviewerExecutionAdmission(x),/aliased|unexpected/)}],
 ["NUL instruction text fails closed",async()=>{const c=await context();assert.throws(()=>admission(c,{instructions:"a\0b"}),/NUL-free/)}],
 ["invalid Unicode scalar instruction fails closed",async()=>{const c=await context();assert.throws(()=>admission(c,{instructions:"\ud800"}),/Unicode scalar/)}],
 ["over-bound task id fails closed",async()=>{const c=await context();assert.throws(()=>admission(c,{taskId:"x".repeat(129)}),/byte bound/)}],
 ["over-bound policy identity fails closed",async()=>{const c=await context();assert.throws(()=>admission(c,{policyIdentity:"x".repeat(129)}),/byte bound/)}],
 ["over-bound instructions fail closed",async()=>{const c=await context();assert.throws(()=>admission(c,{instructions:"x".repeat(8193)}),/byte bound/)}],
 ["provider and model field injection is rejected",async()=>{const c=await context();assert.throws(()=>createO4dO4cReviewerExecutionAdmission({taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:c,provider:"openai",model:"x"}),/unexpected or missing/)}],
 ["credential field injection is rejected",async()=>{const c=await context();assert.throws(()=>createO4dO4cReviewerExecutionAdmission({taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:c,credential:"secret"}),/unexpected or missing/)}],
 ["publication field injection is rejected",async()=>{const c=await context();assert.throws(()=>createO4dO4cReviewerExecutionAdmission({taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:c,publicationTarget:"review"}),/unexpected or missing/)}],
 ["persistence and telemetry field injection is rejected",async()=>{const c=await context();assert.throws(()=>createO4dO4cReviewerExecutionAdmission({taskId:"review-pr-42",policyIdentity:"p",instructions:"i",o4cContext:c,database:"x",telemetry:true}),/unexpected or missing/)}],
 ["forged admission identity fails runtime validation",async()=>{const r={...clone(admission(await context())),admissionIdentity:"f".repeat(64)};assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/admission identity mismatch/)}],
 ["item omission fails runtime validation",async()=>{const r=clone(admission(await context({rows:[changed("a.ts"),changed("z.ts")]}))) as Obj;r.items.pop();assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/identity sequence|accounting|changed-path/)}],
 ["item reordering fails runtime validation",async()=>{const r=clone(admission(await context({rows:[changed("a.ts"),changed("z.ts")]}))) as Obj;r.items.reverse();assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/identity sequence/)}],
 ["changed-path mutation fails runtime validation",async()=>{const r=clone(admission(await context())) as Obj;r.changedPaths=["x.ts"];assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/changed-path sequence|admission identity/)}],
 ["blocked canonical result is accepted by runtime validator",async()=>{const r=admission(await context(),{taskId:"other"});assert.deepEqual(validateO4dO4cReviewerExecutionAdmissionResult(r),r)}],
 ["re-signed text mutation is rejected by exact-byte content binding",async()=>{const r=clone(admission(await context())) as Obj;r.items[0].text="X"+r.items[0].text.slice(1);resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/exact-byte content identity/)}],
 ["re-signed predecessor provenance mutation is rejected",async()=>{const r=clone(admission(await context())) as Obj;r.items[0].provenanceRefs=[...r.items[0].provenanceRefs];r.items[0].provenanceRefs[0]="o4b-content:"+"f".repeat(64);r.items[0].provenanceRefs.sort();resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/predecessor provenance/)}],
 ["re-signed changed path and changed-item reordering is rejected",async()=>{const r=clone(admission(await context({rows:[changed("a.ts"),changed("z.ts")]}))) as Obj;r.changedPaths.reverse();r.items.reverse();r.itemIdentities.reverse();resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/canonical order/)}],
 ["re-signed supporting item reordering is rejected",async()=>{const r=clone(admission(await context({support:["docs/a.md","docs/z.md"]}))) as Obj;const changedItems=r.items.filter((x:Obj)=>x.readRole==="CHANGED_PATH"), supports=r.items.filter((x:Obj)=>x.readRole==="SUPPORTING_CONTEXT").reverse();r.items=[...changedItems,...supports];r.itemIdentities=r.items.map((x:Obj)=>x.itemId);resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/supporting item canonical order/)}],
 ["re-signed omitted supporting path reordering is rejected",async()=>{const r=clone(admission(await context())) as Obj;r.omittedSupportingPaths=["z.md","a.md"];r.omittedSupportingPathCount=2;resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/omitted supporting canonical order/)}],
 ["re-signed revision SHA mutation is rejected against admitted head lineage",async()=>{const r=clone(admission(await context())) as Obj;r.items[0].contentRevisionSha="c".repeat(40);resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/revision SHA/)}],
 ["re-signed changed-file status mutation is rejected",async()=>{const r=clone(admission(await context())) as Obj;r.items[0].changedFileStatus="invented";resign(r);assert.throws(()=>validateO4dO4cReviewerExecutionAdmissionResult(r),/changedFileStatus unsupported/)}],
 ["source static scan proves no forbidden capabilities or K3 impersonation",()=>{const s=readFileSync(new URL("../src/github-review/o4d-o4c-reviewer-execution-admission.ts",import.meta.url),"utf8");for(const bad of ["fetch(","node:fs","node:child_process","process.env","ReviewerExecutionRuntime","ReviewerProvider","ModelProvider","k3-r5-context-bundle-v1","kodac.context.lexical-evidence-v1","OPENAI_API_KEY","GITHUB_TOKEN","writeFile","appendFile","sqlite","postgres","/comments","/reviews"])assert.equal(s.includes(bad),false,bad)}],
 ["implementation surface is exactly the authorized three paths",()=>{for(const u of [new URL("../src/github-review/o4d-o4c-reviewer-execution-admission.ts",import.meta.url),new URL("o4d-o4c-reviewer-execution-admission.test.ts",import.meta.url),new URL("../../../schema/o4d-o4c-reviewer-execution-admission.schema.json",import.meta.url)])assert.equal(existsSync(u),true)}],
 ["schema requires unique item identities and provenance references",()=>{const s=JSON.parse(readFileSync(new URL("../../../schema/o4d-o4c-reviewer-execution-admission.schema.json",import.meta.url),"utf8"));assert.equal(s.properties.itemIdentities.uniqueItems,true);assert.equal(s.$defs.item.properties.provenanceRefs.uniqueItems,true)}],
]
for(const [name,fn] of cases)test(`O4-D: ${name}`,fn)
test("O4-D focused matrix contains at least 30 independently named cases",()=>assert.ok(cases.length>=30))
